### ISSUE TITLE
Wondering how the endpoint was get

### ISSUE THREAD

**Issue by becks9999** [bellingcat/instagram-location-search#19]
Hi
Was wondering where was the endpoint retreive?
    url = "https://www.instagram.com/location_search/"
    params = {"latitude": lat, "longitude": lng, "__a": 1}
    headers = {"Cookie": cookie}

I could not see this endpoint anywhere in the network of instagram.com

Thanks in advance

**Comment by loganwilliams** [comment]
The endpoint is used by the mobile app to find location tag suggestions. You can discover it with CharlesProxy or similar.
