### ISSUE TITLE
Demonstrate a workflow for scraping images near a location

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/instagram-location-search#2]
Currently, this tool only returns location IDs. While these can be manually browser in Instagram's web interface, a common use case might involve scraping images from a number of returned location IDs so that they can be reviewed together.

To better support this use case, `instagram-location-search` could generate a list of location IDs in a format expected by other tools for scraping Instagram images, e.g. https://github.com/arc298/instagram-scraper. This should be demonstrated in documentation.

**Comment by michelezoncheddu** [comment]
I tried instagram-scraper, but it needed a profile to scrape the images from. I didn't manage to use it just for the locations.

Now I switched to instascrape, and it seems to work, but I made a python script that reads the locationIDs from the csv and scrapes the images with instascrape.

I don't know if this is a solution that you are looking for. Let me know.
