### ISSUE TITLE
Now use instagram-scraper to pull down all the photos at those locations: can not use

### ISSUE THREAD

**Issue by youctyu** [bellingcat/instagram-location-search#8]
Now use instagram-scraper to pull down all the photos at those locations:

instagram-scraper @creds.txt --filename @location_ids.txt --location --include-location --destination <output dir>

the command can not use. It errors :
Traceback (most recent call last):
  File "c:\users\ouuo\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ouuo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ouuo\Desktop\ins\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\ouuo\Desktop\ins\lib\site-packages\instagram_scraper\app.py", line 1509, in main
    raise ValueError('Must provide only one of the following: username(s) OR a filename containing username(s) OR --followings-input')
ValueError: Must provide only one of the following: username(s) OR a filename containing username(s) OR --followings-input

**Comment by dpanic** [comment]
I can confirm that ```pip install instagram-scraper``` doesn't install instagram-scraper.

Can you provide url/zip to working instagram-scraper? I found https://archive.is/kYar0#selection-1867.0-1870.0

**Comment by GalenReich** [comment]
Thanks for opening this issue. The problem you're having is with the Instagram Scraper tool, which is a separate 3rd party tool that we don't maintain and is no longer available. I've opened a separate issue #18 to reflect that we shouldn't refer to this tool. Please let us know on that issue if you find a different tool that can make use of the location IDs.

I'm going to close this issue now as it relates to a different tool.
